yarnPath: .yarn/releases/yarn-4.3.0.cjs
defaultSemverRangePrefix: ""

packageExtensions:
  "@chromatic-com/storybook@1.5.0":
    dependencies:
      react: 18.3.1
  "@nextui-org/system-rsc@2.1.2":
    dependencies:
      tailwindcss: 3.4.4
      "@nextui-org/theme": 2.2.5
  "@nextui-org/theme@2.2.5":
    dependencies:
      tailwindcss: 3.4.4
  "@opentelemetry/instrumentation-http@0.52.0":
    dependencies:
      "@opentelemetry/api": 1.9.0
  "@sentry/utils@8.8.0":
    dependencies:
      webpack: 5.91.0
      "@sentry/webpack-plugin": 2.18.0
  "@sentry/nextjs@8.8.0":
    dependencies:
      "@opentelemetry/api": 1.9.0
      "@opentelemetry/core": 1.25.0
      "@opentelemetry/sdk-trace-base": 1.25.0
      "@opentelemetry/instrumentation": 0.52.0
      "@opentelemetry/semantic-conventions": 1.25.0
  "@storybook/core-common@8.1.6":
    dependencies:
      react: 18.3.1
      react-dom: 18.3.1
      typescript: 5.4.3
      "@storybook/nextjs": 8.1.6
  "@storybook/addon-controls@8.1.6":
    dependencies:
      react: 18.3.1
      react-dom: 18.3.1
  "@storybook/addon-onboarding@8.1.6":
    dependencies:
      react: 18.3.1
  "@storybook/nextjs@8.1.6":
    dependencies:
      next: 14.2.3
      webpack: 5.91.0
  "@storybook/manager-api@8.1.6":
    dependencies:
      react: 18.3.1
      react-dom: 18.3.1
  "@strapi/admin@4.24.5":
    dependencies:
      "@strapi/plugin-i18n": 4.24.5
      "@strapi/plugin-email": 4.24.5
      "@strapi/plugin-upload": 4.24.5
      "@strapi/plugin-users-permissions": 4.24.5
      redux: 5.0.1
      reselect: 4.1.8
  "@strapi/design-system@1.19.0":
    dependencies:
      "@codemirror/view": 6.28.0
      "@codemirror/state": 6.4.1
      "@radix-ui/react-focus-guards": 1.0.1
  "@strapi/strapi@4.24.5":
    dependencies:
      react: 18.3.1
      react-is: 18.3.1
      react-dom: 18.3.1
      react-router-dom: 5.3.4
      styled-components: 5.3.3
      "@strapi/plugin-i18n": 4.24.5

      "@strapi/plugin-users-permissions": 4.24.5
  "@typescript-eslint/utils@5.62.0":
    dependencies:
      typescript: 5.4.3
  "@typescript-eslint/utils@7.12.0":
    dependencies:
      typescript: 5.4.3
  "@typescript-eslint/utils@7.13.0":
    dependencies:
      typescript: 5.4.3
  "@typescript-eslint/utils@8.0.0-alpha.28":
    dependencies:
      typescript: 5.4.3
  babel-plugin-styled-components@2.1.4:
    dependencies:
      "@babel/core": 7.24.7
  knex@2.5.0:
    dependencies:
      pg: 8.8.0
  markdown-it@12.3.2:
    dependencies:
      punycode: 2.3.1
  next@14.2.3:
    dependencies:
      react: 18.3.1
  postcss-loader@8.1.1:
    dependencies:
      autoprefixer: 10.4.19
      postcss-pxtorem: 6.1.0
      tailwindcss: 3.4.4
