yarnPath: .yarn/releases/yarn-4.2.2.cjs

packageExtensions:
  # Cms
  "@strapi/strapi@*":
    dependencies:
      "@strapi/plugin-users-permissions": "4.24.5"
      "@strapi/plugin-i18n": "4.24.5"
  "@strapi/admin@*":
    dependencies:
      "@strapi/plugin-users-permissions": "4.24.5"
      "@strapi/plugin-email": "4.24.5"
      "@strapi/plugin-i18n": "4.24.5"
      "react": "^18.3.1"
      "react-dom": "^18.3.1"
      "react-router-dom": "5.3.4"
      "redux": "^5.0.1"
      "reselect": "4.1.8"
      "styled-components": "5.3.3"
  "@strapi/design-system@*":
    dependencies:
      "@radix-ui/react-focus-guards": "^1.0.1"
      "@codemirror/state": "^6.4.1"
      "@codemirror/view": "^6.27.0"
  "@strapi/plugin-content-type-builder@*":
    dependencies:
      "react": "^18.3.1"
  "@strapi/plugin-email@*":
    dependencies:
      "react": "^18.3.1"
  "@strapi/plugin-upload@*":
    dependencies:
      "react": "^18.3.1"
  "@strapi/content-releases@*":
    dependencies:
      "react": "^18.3.1"
  "use-context-selector@*":
    dependencies:
      "scheduler": "^0.23.2"
  "markdown-it@*":
    dependencies:
      "punycode": "^2.3.1"
  "knex@*":
    dependencies:
      "pg": "8.8.0"

  # Client
  "@nextui-org/system-rsc@*":
    dependencies:
      "@nextui-org/theme": "^2.2.5"
  "@nextui-org/theme@*":
    dependencies:
      "tailwindcss": "^3.4.4"
  "@storybook/core-common@*":
    dependencies:
      "@storybook/nextjs": "^8.1.6"
  "@storybook/nextjs@*":
    dependencies:
      "webpack": "^5.91.0"
      "next": "14.2.3"
  "next@*":
    dependencies:
      "react": "^18.3.1"
  "postcss-loader@*":
    dependencies:
      "tailwindcss": "^3.4.4"
      "autoprefixer": "^10.4.19"
      "postcss-pxtorem": "^6.1.0"
  "@opentelemetry/instrumentation-http@*":
    dependencies:
      "@opentelemetry/api": "^1.8.0"
  "@sentry/utils@*":
    dependencies:
      "@sentry/webpack-plugin": "^2.18.0"
