import type { Metadata } from "next"

import { Footer } from "@/widgets/footer"
import { Header } from "@/widgets/header"

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function PublicLayout({ children }: Readonly<{ children: React.ReactNode }>) {
	return (
		<div className="relative flex min-h-screen flex-col">
			<Header />
			<main className="flex-grow">{children}</main>
			<Footer />
		</div>
	)
}
